services:
  # ─────────────────────────────────────────
  #  UPTIME KUMA – Monitoring
  # ─────────────────────────────────────────
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ${CONFIG}/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    ports:
      - "3003:3001"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.kuma-lan.rule=Host(`kuma.lan`)
      - traefik.http.routers.kuma-lan.entrypoints=web
      - traefik.http.services.kuma-lan.loadbalancer.server.port=3001
networks:
  proxy:
    external: true
